"use client";

import { NeonSuggestion } from "@/types/dashboard";
import { motion } from "framer-motion";

interface SuggestionsListProps {
  suggestions: NeonSuggestion[];
}

export function SuggestionsList({ suggestions }: SuggestionsListProps) {
  return (
    <article className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6">
      <header className="flex flex-col gap-1">
        <h2 className="text-lg font-semibold text-white">AI Recommendations</h2>
        <p className="text-sm text-slate-400">
          Generated by the NeonCheck AI engine combining audit, SERP, and sentiment signals.
        </p>
      </header>
      <div className="mt-6 space-y-4">
        {suggestions.map((suggestion, index) => (
          <motion.div
            key={suggestion.id}
            className="rounded-xl border border-slate-800/60 bg-slate-900/60 p-4"
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.04 }}
          >
            <p className="text-xs uppercase tracking-wide text-neon-blue">{suggestion.type}</p>
            <p className="mt-1 font-medium text-white">{suggestion.message}</p>
            <p className="mt-2 text-xs text-slate-400">
              {new Date(suggestion.createdAt).toLocaleString()}
            </p>
          </motion.div>
        ))}
        {suggestions.length === 0 && (
          <p className="text-sm text-slate-500">
            The AI engine is preparing personalized suggestions. Check back shortly!
          </p>
        )}
      </div>
    </article>
  );
}
